package sss.ui.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.*;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class NobuMainDesign extends HorizontalLayout {
	protected CssLayout menuItems;
	protected Button writeButton;
	protected Button statusButton;
	protected Button inboxButton;
	protected Button archiveButton;
	protected Button settingsButton;
	protected Button schedulesButton;
	protected Button sentButton;
	protected Button logoutButton;
	protected VerticalLayout content;
	protected HorizontalLayout statusLayout;
	protected Button balanceCptnBtn;
	protected Button balanceValuBtnLbl;
	protected Button prevButton;
	protected Button nextButton;
	protected Panel itemPanel;
	protected VerticalLayout itemPanelVerticalLayout;

	public NobuMainDesign() {
		Design.read(this);
	}
}
