object Vers {
  val akkaVer = "2.5.+"
  val scryptoVer = "1.2.0-RC3"
  val ancillaryVer = "1.5-SNAPSHOT"
  val scalacticVer = "3.0.5"
  val scalatraVer = "2.6.3"
  val sssDbVer = "0.9.36-SNAPSHOT"
  val sssVaadinReact = "0.4-SNAPSHOT"
  val hsqldbVer = "2.4.1"
  val twitterColVer = "18.5.0"
  val consoleUtilVer = "0.1.4"
  val sprayJsonVer = "1.3.2"
  val restyVer = "0.3.2"
  val commonsNetVer = "3.+"
  val vaadinVer = "8.5.2"
}
