package sss.ui.milford.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Image;
import com.vaadin.ui.Link;
import com.vaadin.ui.Label;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Button;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Message extends VerticalLayout {
    protected Panel messageHeader;
    protected Image senderImage;
    protected Link messageSender;
    protected Label receivedAt;
    protected CssLayout topBtnLayout;
    protected Button keepPost;
    protected Button deletePost;
    protected Panel messageBody;

    public Message() {
        Design.read(this);
    }
}
