package sss.ui.milford.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Structure extends VerticalLayout {
    protected Button openstarLogo;
    protected CssLayout searchGroup;
    protected TextField searchField;
    protected Button searchBtn;
    protected CssLayout lhs;
    protected CssLayout menuItems;
    protected Button statusButton;
    protected Button inboxButton;
    protected Button archiveButton;
    protected Button sentButton;
    protected Button junkButton;
    protected Button settingsButton;
    protected Button logoutButton;
    protected VerticalLayout content;
    protected HorizontalLayout statusLayout;
    protected Button balanceCptnBtn;
    protected Button balanceValuBtnLbl;
    protected Button prevButton;
    protected Button nextButton;
    protected Panel itemPanel;
    protected VerticalLayout itemPanelVerticalLayout;
    protected CssLayout rhs;

    public Structure() {
        Design.read(this);
    }
}
